In [1]:
!pwd
!cd /playground/10714/hw4

/playground/10714/hw4


In [2]:
# clean
!rm -rf ./.hypothesis
!rm -rf ./.pytest_cache
!rm -rf ./build
!rm -rf ./python/needle/__pycache__
!rm -rf ./python/needle/backend_ndarray/__pycache__
!rm -rf ./python/needle/backend_ndarray/*.so

In [3]:
!make

-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python: /opt/conda/bin/python3.10 (found version "3.10.9") found components: Development Interpreter Development.Module Development.Embed 
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Found pybind11: /opt/conda/lib/python3.10/site-packages/pybind11/include (found version "2.11.1")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create

In [4]:
import sys
sys.path.append('./python')

In [5]:
!python3 -m pytest -l -v -k "nd_backend"

============================= test session starts ==============================
platform linux -- Python 3.10.9, pytest-7.4.0, pluggy-1.0.0 -- /opt/conda/bin/python3
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/playground/10714/hw4/.hypothesis/examples')
rootdir: /playground/10714/hw4
plugins: hypothesis-6.70.0, anyio-3.7.0
collected 1803 items / 1685 deselected / 118 selected                          

tests/test_nd_backend.py::test_ewise_fn[cpu-shape0-divide] PASSED        [  0%]
tests/test_nd_backend.py::test_ewise_fn[cpu-shape0-subtract] PASSED      [  1%]
tests/test_nd_backend.py::test_ewise_fn[cpu-shape1-divide] PASSED        [  2%]
tests/test_nd_backend.py::test_ewise_fn[cpu-shape1-subtract] PASSED      [  3%]
tests/test_nd_backend.py::test_ewise_fn[cuda-shape0-divide] PASSED       [  4%]
tests/test_nd_backend.py::test_ewise_fn[cuda-shape0-subtract] PASSED     [  5%]
tests/test_nd_backend.py::test_ewise_fn[cuda-shape1-divide] 

In [6]:
!python3 -m pytest -l -v -k "op_conv and forward"

============================= test session starts ==============================
platform linux -- Python 3.10.9, pytest-7.4.0, pluggy-1.0.0 -- /opt/conda/bin/python3
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/playground/10714/hw4/.hypothesis/examples')
rootdir: /playground/10714/hw4
plugins: hypothesis-6.70.0, anyio-3.7.0
collected 1803 items / 1769 deselected / 34 selected                           

tests/test_conv.py::test_op_conv[forward-needle.backend_ndarray.ndarray_backend_cpu-Z_shape0-W_shape0-1-0] PASSED [  2%]
tests/test_conv.py::test_op_conv[forward-needle.backend_ndarray.ndarray_backend_cpu-Z_shape1-W_shape1-1-1] PASSED [  5%]
tests/test_conv.py::test_op_conv[forward-needle.backend_ndarray.ndarray_backend_cpu-Z_shape2-W_shape2-1-2] PASSED [  8%]
tests/test_conv.py::test_op_conv[forward-needle.backend_ndarray.ndarray_backend_cpu-Z_shape3-W_shape3-1-0] PASSED [ 11%]
tests/test_conv.py::test_op_conv[forward-needle.backend_

In [7]:
!python3 -m pytest -l -v -k "op_conv and backward"

============================= test session starts ==============================
platform linux -- Python 3.10.9, pytest-7.4.0, pluggy-1.0.0 -- /opt/conda/bin/python3
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/playground/10714/hw4/.hypothesis/examples')
rootdir: /playground/10714/hw4
plugins: hypothesis-6.70.0, anyio-3.7.0
collected 1803 items / 1769 deselected / 34 selected                           

tests/test_conv.py::test_op_conv[backward-needle.backend_ndarray.ndarray_backend_cpu-Z_shape0-W_shape0-1-0] PASSED [  2%]
tests/test_conv.py::test_op_conv[backward-needle.backend_ndarray.ndarray_backend_cpu-Z_shape1-W_shape1-1-1] PASSED [  5%]
tests/test_conv.py::test_op_conv[backward-needle.backend_ndarray.ndarray_backend_cpu-Z_shape2-W_shape2-1-2] PASSED [  8%]
tests/test_conv.py::test_op_conv[backward-needle.backend_ndarray.ndarray_backend_cpu-Z_shape3-W_shape3-1-0] PASSED [ 11%]
tests/test_conv.py::test_op_conv[backward-needle.bac

In [8]:
!python3 -m pytest -l -v -k "flip"

============================= test session starts ==============================
platform linux -- Python 3.10.9, pytest-7.4.0, pluggy-1.0.0 -- /opt/conda/bin/python3
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/playground/10714/hw4/.hypothesis/examples')
rootdir: /playground/10714/hw4
plugins: hypothesis-6.70.0, anyio-3.7.0
collected 1803 items / 1763 deselected / 40 selected                           

tests/test_conv.py::test_flip_forward[params0-needle.backend_ndarray.ndarray_backend_cpu] PASSED [  2%]
tests/test_conv.py::test_flip_forward[params0-needle.backend_ndarray.ndarray_backend_cuda] PASSED [  5%]
tests/test_conv.py::test_flip_forward[params1-needle.backend_ndarray.ndarray_backend_cpu] PASSED [  7%]
tests/test_conv.py::test_flip_forward[params1-needle.backend_ndarray.ndarray_backend_cuda] PASSED [ 10%]
tests/test_conv.py::test_flip_forward[params2-needle.backend_ndarray.ndarray_backend_cpu] PASSED [ 12%]
tests/test_conv.py

In [9]:
!python3 -m pytest -l -v -k "nn_conv_backward"

============================= test session starts ==============================
platform linux -- Python 3.10.9, pytest-7.4.0, pluggy-1.0.0 -- /opt/conda/bin/python3
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/playground/10714/hw4/.hypothesis/examples')
rootdir: /playground/10714/hw4
plugins: hypothesis-6.70.0, anyio-3.7.0
collected 1803 items / 1789 deselected / 14 selected                           

tests/test_conv.py::test_nn_conv_backward[needle.backend_ndarray.ndarray_backend_cpu-4-1-1-3-1] PASSED [  7%]
tests/test_conv.py::test_nn_conv_backward[needle.backend_ndarray.ndarray_backend_cpu-14-8-16-3-1] PASSED [ 14%]
tests/test_conv.py::test_nn_conv_backward[needle.backend_ndarray.ndarray_backend_cpu-14-8-16-3-2] PASSED [ 21%]
tests/test_conv.py::test_nn_conv_backward[needle.backend_ndarray.ndarray_backend_cpu-14-8-8-3-1] PASSED [ 28%]
tests/test_conv.py::test_nn_conv_backward[needle.backend_ndarray.ndarray_backend_cpu-14-8-8-3-2

# playground
    测试一些函数和算子的具体功能
* ops/Max

In [10]:
ndim = 3
axis = 1
tuple([a for a in range(ndim) if a != axis]) + (axis,)

(0, 2, 1)

In [11]:
import sys
sys.path.append('./python')

import numpy
import needle as ndl


def calc_numpy_max_mask(axis, keepdims, npz):
    """
        使用numpy计算，逻辑上是正确的。但是由于是cpu计算，会拖慢整体计算速度。
        先保证逻辑上的正确性吧。
    """
    npz_max = numpy.max(npz, axis=axis, keepdims=keepdims)
    print("npz_max",npz_max.shape, "\n", npz_max)

    max_axes = axis
    if axis is None:
        max_axes = list(range(len(npz.shape)))
    max_shape = list(npz.shape)
    for ax in max_axes:
        max_shape[ax] = 1
                
    if keepdims == False:
        npz_max = npz_max.reshape(max_shape)

    np_all_max =  numpy.broadcast_to(npz_max, npz.shape)
    print("np_all_max", np_all_max.shape,"\n",np_all_max)

    npmask =  numpy.float32(npz == np_all_max)
    # 注意维度相同的两个max值需要均分
    if axis == None:
        npmask = npmask / numpy.sum(npmask, axis=axis)
    else:
        npmask /= numpy.sum(npmask, axis=axis, keepdims=True)
    return npmask

# 使用numpy计算max id
axis = (1,)
# axis = None
keepdims = False
# Z = numpy.random.rand(2,3,2)
Z = numpy.array([[2,1],[1,2]]) 
print("npz", Z.shape, "\n",Z)

mask = calc_numpy_max_mask(axis, keepdims,Z)
mask = ndl.Tensor(ndl.NDArray(mask), requires_grad=False)
print("npz_mask", mask.shape,"\n",mask)

npz (2, 2) 
 [[2 1]
 [1 2]]
npz_max (2,) 
 [2 2]
np_all_max (2, 2) 
 [[2 2]
 [2 2]]
npz_mask (2, 2) 
 [[1. 0.]
 [0. 1.]]


In [12]:
import torch
a = torch.nn.Parameter(torch.randn(3, 4))
a = torch.tensor([[1,2],[1,2]], requires_grad =True, dtype=torch.float32)
print(a)

y = torch.max(a, dim=1).values
print(y)

torch.sum(y).backward()
print(a.grad)


tensor([[1., 2.],
        [1., 2.]], requires_grad=True)
tensor([2., 2.], grad_fn=<MaxBackward0>)
tensor([[0., 1.],
        [0., 1.]])


In [13]:
# test ops.Max()
import needle as ndl
a = [[2,2],[1,2]]

keepdims = True
axis = None
device = ndl.backend_ndarray.cuda()
a = ndl.Tensor(ndl.NDArray(a, device=device), requires_grad=True, device=device)

y = ndl.ops.max(a, axis=axis, keepdims=keepdims)
print("a\n", a, '\ny\n', y)
y.backward()

print()
print(a.grad)



a
 [[2. 2.]
 [1. 2.]] 
y
 [[2.]]

[[0.33333334 0.33333334]
 [0.         0.33333334]]


# test nn.LogSumExp()

In [14]:
import torch
import sys
sys.path.append('./python')

import numpy
import needle as ndl

In [15]:
keepdims = False
axis = 1
a = [[2.0,2.0],[1.0,2.0]]

In [16]:
# 使用pytorch做对比
def torch_LSE(Z, axis=None, keepdims=False):
    
    if axis == None:
        max_Z1 = torch.max(Z)
        max_Z2 = max_Z1
    else:
        max_Z1 = torch.max(Z, dim=axis, keepdim=True).values
        max_Z2 = torch.max(Z, axis=axis, keepdims=keepdims).values

    return torch.log(torch.sum(torch.exp(Z-max_Z1), dim=axis, keepdims=keepdims)) + max_Z2

x = torch.tensor(a, requires_grad=True, dtype=torch.float32)
y = torch_LSE(x,axis=axis, keepdims=keepdims)
torch.sum(y).backward()

print(y)
print("grad-torch-搭积木", x.grad)


tensor([2.6931, 2.3133], grad_fn=<AddBackward0>)
grad-torch-搭积木 tensor([[0.5000, 0.5000],
        [0.2689, 0.7311]])


In [17]:
# 使用pytorch做对比

x = torch.tensor(a, requires_grad=True, dtype=torch.float32)
y = torch.logsumexp(x, dim=axis,keepdim=keepdims)
torch.sum(y).backward()

print(y)
print("grad-torch-func", x.grad)

tensor([2.6931, 2.3133], grad_fn=<LogsumexpBackward0>)
grad-torch-func tensor([[0.5000, 0.5000],
        [0.2689, 0.7311]])


In [18]:
# needle 使用nn实现
lse = ndl.nn.LogSumExp()
device = ndl.backend_ndarray.cuda()

x = ndl.Tensor(ndl.NDArray(a, device=device), requires_grad=True, device=device)

y = lse.forward(x, axis=axis, keepdims=keepdims)
y.backward()

print(y)
print("grad-nn", x.grad)

# 侧面佐证max实现的是对的，nn.LogSumExp 也没有什么问题。但是有个问题todo，summation不支持keepdims=True

[2.6931472 2.3132617]
grad-nn [[0.5        0.5       ]
 [0.26894143 0.7310586 ]]


In [19]:
# needle 使用ops实现
device = ndl.backend_ndarray.cuda()
x1 = ndl.Tensor(ndl.NDArray(a, device=device), requires_grad=True, device=device)

y = ndl.ops.logsumexp(x1, axes=axis)
y.backward()

print("y\n",y)
print("grad-ops", x1.grad)

# max的反向细节存在不确定性
# 但是使用nn.LogSumExp 时又与pytorch一致。
    # 大致上应该时数据类型导致在max时的行为不一致。

y
 [2.6931472 2.3132617]
grad-ops [[0.75       0.75      ]
 [0.26894143 1.        ]]


In [20]:
# 和pytorch对比，看看那一步的梯度计算不符合

x = torch.tensor(a, requires_grad=True, dtype=torch.float32)
z2 = torch.tensor(a, requires_grad=True, dtype=torch.float32)
z1 = torch.tensor(a, requires_grad=True, dtype=torch.float32)
print(x)

if axis == None:
    max_Z1 = torch.max(x)
    max_Z2 = max_Z1

else:
   
    max_Z2 = torch.max(z2, dim=axis, keepdim=True).values.broadcast_to(x.shape)
    mask = torch.max(z2, dim=axis, keepdim=True).indices
    print("z2", z2)
    print("max mask", mask)
    max_Z1 = torch.max(z1, axis=axis, keepdims=keepdims).values
    
    

max_Z1.retain_grad()
max_Z2.retain_grad()

yminus = x-max_Z2
yexp = torch.exp(yminus)
ysum = torch.sum(yexp, dim=axis, keepdims=keepdims)
y = torch.log(ysum) + max_Z1

yminus.retain_grad()
yexp.retain_grad()
ysum.retain_grad()
y.retain_grad()

torch.sum(y).backward()

print("\nops.logsumexp",
        "\nd_log\n", ysum.grad,
        "\nd_sum\n", yexp.grad,
        "\nd_exp\n", yminus.grad,
        "\ndz1\n", z1.grad,
         "\ndz\n",x.grad,
        "\ndzmax\n", z2.grad,
        "\ndz2\n", yminus.grad+z2.grad,
        "\nx\n", x.grad+z1.grad+z2.grad)

tensor([[2., 2.],
        [1., 2.]], requires_grad=True)
z2 tensor([[2., 2.],
        [1., 2.]], requires_grad=True)
max mask tensor([[0],
        [1]])

ops.logsumexp 
d_log
 tensor([0.5000, 0.7311]) 
d_sum
 tensor([[0.5000, 0.5000],
        [0.7311, 0.7311]]) 
d_exp
 tensor([[0.5000, 0.5000],
        [0.2689, 0.7311]]) 
dz1
 tensor([[1., 0.],
        [0., 1.]]) 
dz
 tensor([[0.5000, 0.5000],
        [0.2689, 0.7311]]) 
dzmax
 tensor([[-1.,  0.],
        [ 0., -1.]]) 
dz2
 tensor([[-0.5000,  0.5000],
        [ 0.2689, -0.2689]]) 
x
 tensor([[0.5000, 0.5000],
        [0.2689, 0.7311]])
